name: Generate synchronization pattern files

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'tool/**'
      - '!**.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'tool/**'
      - '!**.md'
  workflow_dispatch:
    inputs:
      deploy:
        description: Deploy to the web site
        type: boolean

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: |
        set -e
        sudo apt update
        sudo apt install -y ffmpeg
        pip3 install -U -r tool/requirements.txt

    - name: Generate video files
      run: |
        set -e
        ./docs/generate-pattern.sh -outdir _site

    - name: Upload files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site/

  deploy:
    needs: generate

    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.deploy)

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
